version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    working_dir: /app/api

  dashboard:
    build:
      context: .
      dockerfile: ./dashboard/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
    working_dir: /app/dashboard
    depends_on:
      - api